dist: trusty

language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_install:
  - ./.travis/before_install.sh

script:
  - ./mvnw test -B

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: ExpediaDotCom/graphql-kotlin
      branch: master
      jdk: oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - bex-api@expedia.com
