dist: trusty

language: java
jdk:
  - openjdk8
  - openjdk11

branches:
  only:
    - master
    - /\d+\.\d+\.(x|\d+)/

cache:
  directories:
    - $HOME/.m2

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

script:
  - ./mvnw install
  - ./mvnw -f example/pom.xml verify

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: ExpediaDotCom/graphql-kotlin
    tags: true
    jdk: openjdk8
    all_branches: true

after_deploy:
  - .travis/update-version.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - bex-api@expedia.com
