dist: trusty

language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install:
  - ./mvnw --batch-mode install -B -V

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: ExpediaDotCom/graphql-java
    condition: $TRAVIS_PULL_REQUEST = false

notifications:
  email:
    - bex-api@expedia.com