#
# codecov.io Configuration
# See the docs here: https://docs.codecov.io/docs/codecov-yaml
#
# To verify changes locally, run a gradle build then run the following command from the root:
#
#   bash <(curl -s https://codecov.io/bash)
#

# Ingore the example apps and docs from coverage reports
ignore:
  - "examples/**"
  - "website/**"
  - "docs/**"
