graphql:
  federation:
    enabled: true
    tracing:
      enabled: true
      debug: true
  packages:
    - "com.expediagroup.graphql.examples.federation.extend"

server:
  port: 8081

spring:
  application:
    name: extend-app
