name: Continuous Integration

on:
  push:
    branches:
      - master
      - '*.x.x'
    paths-ignore:
      - 'docs/**'
      - 'website/**'

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions
        java: [ 8, 11.0.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Set up Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.java }}-gradle-

      - name: Build libraries with Gradle
        run: ./gradlew clean build

      - name: Build examples with Gradle
        working-directory: examples
        run: ./gradlew clean build

  release-notes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
