name: Maven CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'
      - name: Build with Maven
        run: ./mvnw clean verify -PdefaultBuild
