name: Maven CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Active Maven profiles
        run: mvn help:active-profiles -P defaultBuild
      - name: Build with Maven
        run: mvn clean verify -P defaultBuild
