name: Pull Request Check Documentation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'website/**'
      - 'perf-tests/**'

jobs:
  check-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Build docs
      if: github.repository == 'ExpediaGroup/graphql-kotlin'
      run: |
        cd website
        npm install
        npm run build

  check-perf-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build perf-tests
        if: github.repository == 'ExpediaGroup/graphql-kotlin'
        run: |
          cd perf-tests
          npm install
