name: Pull Request Check

on:
  pull_request:
    branches:
      - master
      - '*.x.x'
    paths-ignore:
      - 'docs/**'
      - 'website/**'

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions
        java: [ 8, 11.0.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Set up Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.java }}-gradle-

      # Used by maven-plugin integration tests
      - name: Set up Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.java }}-maven-

      - name: Build library with Gradle
        run: ./gradlew clean build

      - name: Archive build reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-reports-${{ matrix.java }}
          path: |
            ./**/build/reports
            plugins/graphql-kotlin-maven-plugin/build/integration/**/build.log
            plugins/graphql-kotlin-maven-plugin/build/integration/**/target/surefire-reports
          retention-days: 7

      - name: Build examples with Gradle
        working-directory: examples
        run: ./gradlew clean build
