name: Pull Request Check Documentation

on:
  pull_request:
    branches:
      - master
      - '*.x.x'
    paths:
      - 'docs/**'
      - 'website/**'

jobs:
  timeout-minutes: 10
  check-docs:
    runs-on: ubuntu-latest
    if: github.repository == 'ExpediaGroup/graphql-kotlin'

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('website/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build website
      run: |
        cd website
        npm install
        npm run build
