name: Publish Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'website/**'

jobs:
  publish-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
       
    - name: Run npm commands
      if: github.repository == 'ExpediaGroup/graphql-kotlin'
      run: |
        cd website
        npm install
        git config --global user.name "${GITHUB_ACTOR}"
        echo "machine github.com login ${GITHUB_ACTOR} password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
        GIT_USER="${GITHUB_ACTOR}" npm run publish-gh-pages
      env:
        CI: true
        CURRENT_BRANCH: master
