name: Publish Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'website/**'

jobs:
  publish-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Run npm commands
      if: github.repository == 'ExpediaGroup/graphql-kotlin'
      run: |
        cd website
        npm install
        git config --global user.name "${GH_USERNAME}"
        echo "machine github.com login ${GH_USERNAME} password ${{ secrets.EG_CI_USER_TOKEN }}" > ~/.netrc
        GIT_USER="${GH_USERNAME}" npm run publish-gh-pages
      env:
        CI: true
        CURRENT_BRANCH: master

        # The following settings will only work with the personal access token we are using
        # Until GH Actions have a way to publish directly we are using this method
        GH_USERNAME: eg-oss-ci
