name: Publish Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'website/**'

jobs:
  publish-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
       
    - name: Run npm commands
      run: |
        cd website
        npm install
        npm run publish-gh-pages
      env:
        CI: true
        CURRENT_BRANCH: master
        USE_SSH: true
