name: Release

on:
  release:
    types: [published]

jobs:
  release-code:
    runs-on: ubuntu-latest
    if: github.repository == 'ExpediaGroup/graphql-kotlin'

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        # dokka doesn't support Java 11
        with:
          java-version: 1.8

      - name: Build library with Gradle
        run: ./gradlew clean build

      - name: Publish library with Gradle
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          ./gradlew :initializeSonatypeStagingRepository publish :closeAndReleaseRepository publishPlugins -Pversion=${NEW_VERSION}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          PLUGIN_PORTAL_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          PLUGIN_PORTAL_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

  release-docs:
    runs-on: ubuntu-latest
    if: github.repository == 'ExpediaGroup/graphql-kotlin'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('website/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build website
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          cd website
          npm install
          npm run version $NEW_VERSION
          npm run build

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build/graphql-kotlin
          user_name: eg-oss-ci
          user_email: oss@expediagroup.com

      - name: Commit new files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Add new docs version"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
