name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        # dokka doesn't support Java 11
        with:
          java-version: 1.8
      - name: Set up Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build library with Gradle
        run: ./gradlew clean build
      - name: Publish library with Gradle
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          ./gradlew publish -Pversion=${NEW_VERSION}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

